# Generated by Django 5.2.16 on 2026-07-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_bio_user_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="balance",
        ),
        migrations.AddField(
            model_name="user",
            name="failed_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
