# Generated by Django 5.2.16 on 2026-07-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_balance_user_failed_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name="user",
            name="is_dormant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
