# Generated by Django 5.2.16 on 2026-07-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
